services:
  cod2x_server:
    image: cod2x:latest
    container_name: cod2x
    restart: unless-stopped
    ports:
      - "20500:20500/udp"
      - "20510:20510/udp"
      - "28960:28960/tcp"
      - "28960:28960/udp"
      - "20700:20700/udp"
      - "20710:20710/udp"
      - "20720:20720/udp"
    volumes:
      - ./main:/home/cod2/main
    command:
      [
        "+set net_port 28960",
        "+set sv_update 0",
        "+set sv_punkbuster 0",
        "+exec server.cfg"
      ]
    stdin_open: true
    tty: true